title: Anna Reithmeir # your name (or website title) here
logo: "/images/anna2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's student of Informatics at TU Munich
  <br><br>
  24, Munich based
  <br><br>
  <a href="https://www.linkedin.com/in/anna-reithmeir-a45bb7165/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
